menu:
  button:
  - name: "Photo Action"
    sub_button:
    - type: "pic_sysphoto"
      name: "拍照图片"
      key: "takephoto"
    - type: "pic_photo_or_album"
      name: "选择图片"
      key: "selectphoto"

  - name: "Web Action"
    sub_button:
    - type: "view"
      name: "公司简介"
      url: "http://wechat.afeil.com/articles/1"
    - type: "view"
      name: "功能页"
      url: "http://wechat.afeil.com/home"

